### PR TITLE
Fix comparison within is_time() method

### LINKED ISSUE #5: Logic Issue: Setup_date() never triggered from is_time() method
There was an issue introduced in 66baf1dbd939f3cb97723a01449f6d54dee9a970 that's breaking things a bit; by casting this to an int the strict check for `false` will never evaluate to true.

```
$installed = (int) get_option( $this->key, false );

if ( false === $installed ) {
	$this->setup_date();
	$installed = time();
}
```

Either the comparison should be adjusted to be a loose comparison check, or to compare based on the int. Based on the code I'd suggest the later....

```
$installed = (int) get_option( $this->key, false );

if ( 0 === $installed ) {
	$this->setup_date();
	$installed = time();
}
```

### PR DESCRIPTION
**Pull request by mallardduck**
Using false here is causing the check to ALWAYS evaluate as false since the value is being cast to an int. A check of `bool === int` can never be true, so updating this to comparing for 0 is the best solution.

This PR will fix #5

### CODE REVIEW

File: review.php [hunk 1]
```diff
@@ -240,7 +240,7 @@ public function is_time() {
 
 			$installed = (int) get_option( $this->key, false );
 
-			if ( false === $installed ) {
+			if ( 0 === $installed ) {
```
Comment (julien731) [inline review.php:243]: That's a very good point! Comparing to `0` works for me, but, in this case, we should also set the default value of `get_option()` to `0` as well instead of `false`. Better prepare exactly for what we need instead of relying on a typecast.

```
$installed = (int) get_option( $this->key, 0 );
```

**Review by julien731 — CHANGES_REQUESTED** [review]

File: review.php (hunk 1 above)
Comment (mallardduck) [reply review.php:243]: Hi - it's me - apparently I was terrible at following up with this! Sorry about that.
Updated now.
